<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Cover Screen</title>
    <link rel="stylesheet" href="/static/css/screen.css">
</head>
<body>
    <div class="screen">
        <div class="slides"></div>
        <progress class="iteration-progress"></progress>
        <template data-error-template>
            <div class="slide">
                Something went wrong!
            </div>
        </template>
        <template data-image-slide-template>
            <figure class="slide">
                <img>
            </figure>
        </template>
        <template data-web-slide-template>
            <div class="slide">
                <iframe
                    frameborder="0"
                    referrerpolicy="no-referrer"
                    sandbox="allow-scripts"
                ></iframe>
            </div>
        </template>
    </div>
    <script src="/static/js/screen.js"></script>
</body>
</html>
